name: whats_clone
description: "it's try to make whats app clone to apply concepts real time data"

publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  # firebase dependencies and supabase
  firebase_core: ^3.8.1
  firebase_messaging: ^15.2.5
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  firebase_database: ^11.2.0
  supabase_flutter: ^2.8.2
  google_sign_in: ^6.2.1
  googleapis_auth: ^1.6.0
  firebase_crashlytics: ^4.3.5
  # code generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  #router
  go_router: ^14.6.2
  # local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  #contact and phone number
  fast_contacts: ^4.0.0
  country_code_picker_plus: ^0.0.9
  dlibphonenumber: ^1.1.29


  # other dependencies
  http: ^1.3.0
  flutter_local_notifications: ^18.0.1
  logger: ^2.5.0
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  image_picker: ^1.1.2
  image: ^4.5.2
  flutter_riverpod: ^2.6.1
  rxdart: ^0.28.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1

  flutter_localizations:
    sdk: flutter
  intl: any




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1
  riverpod_generator: ^2.6.3

  icons_launcher: ^3.0.0
  flutter_native_splash: ^2.4.4

flutter:

  uses-material-design: true
  generate: true


  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Mulish-VariableFont_wght.ttf
