// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfNAFqTroeSTB2pIEn-iz6mDEvJ5GPhPQ',
    appId: '1:39690319251:web:3eda459939005d0e8de466',
    messagingSenderId: '39690319251',
    projectId: 'whats-clone-62037',
    authDomain: 'whats-clone-62037.firebaseapp.com',
    storageBucket: 'whats-clone-62037.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV5PpNvqg4MgpBy_LPoyncfd84p3RaT2Y',
    appId: '1:39690319251:android:b812579772df1c728de466',
    messagingSenderId: '39690319251',
    projectId: 'whats-clone-62037',
    storageBucket: 'whats-clone-62037.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASGMtNV5AODZM_aN8dG4yftJVB-UO9Yyg',
    appId: '1:39690319251:ios:816ae2b7c11b78c28de466',
    messagingSenderId: '39690319251',
    projectId: 'whats-clone-62037',
    storageBucket: 'whats-clone-62037.firebasestorage.app',
    iosBundleId: 'com.mohammedramadan.whatsClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASGMtNV5AODZM_aN8dG4yftJVB-UO9Yyg',
    appId: '1:39690319251:ios:816ae2b7c11b78c28de466',
    messagingSenderId: '39690319251',
    projectId: 'whats-clone-62037',
    storageBucket: 'whats-clone-62037.firebasestorage.app',
    iosBundleId: 'com.mohammedramadan.whatsClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfNAFqTroeSTB2pIEn-iz6mDEvJ5GPhPQ',
    appId: '1:39690319251:web:1a06929e91d1feda8de466',
    messagingSenderId: '39690319251',
    projectId: 'whats-clone-62037',
    authDomain: 'whats-clone-62037.firebaseapp.com',
    storageBucket: 'whats-clone-62037.firebasestorage.app',
  );
}
